### ISSUE TITLE
undefined method `token' in version 0.1.4 of the gem

### ISSUE THREAD

**Issue by thb** [nsanta/fbgraph#9]
With version 0.0.9:

> > client.selection.me.picture
> > /me/picture
> > => "https://graph.facebook.com/me/picture?access_token=XXX"

With version 0.1.4:

> > client.selection.me.picture
> > NoMethodError: undefined method `token' for #<RestClient::Resource:0xb65ffff8>
> >     from /usr/lib/ruby/gems/1.8/gems/fbgraph-0.1.4/lib/fbgraph/selection.rb:44:in`picture'
> >     from (irb):6

**Comment by nsanta** [comment]
fixed on master

**Comment by nsanta** [comment]
closed

**Comment by websymphony** [comment]
I am still getting the same error. Am on version 0.1.4 and rails 3.0.0

**Comment by nsanta** [comment]
update the version

**Comment by websymphony** [comment]
Sorry to bug you again, but I am already on 0.1.4, isn't it the latest version?

**Comment by nsanta** [comment]
the last version is 0.1.6 and was released 1 hour ago

**Comment by websymphony** [comment]
Just updated it.
Now when I use the following call: client.selection.me.picture
It is being resolved to following URL: 
https://graph.facebook.comme/picture?access_token=xxxxxxx
Instead of: 
https://graph.facebook.com/me/picture?access_token=xxxxxxx

**Comment by nsanta** [comment]
bumped new version with fix

**Comment by websymphony** [comment]
Awesome! Thanks  a bunch. :)

**Comment by nsanta** [comment]
Thanks to you. Was my fault and i try to keep the users happy.
